config/routes.rb
Rails.application.routes.draw do
  resources :names
  root "names#index"

end

app/models/name.rb
class Name < ActiveRecord::Base
  default_scope -> {order("created_at DESC")}
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  before_action :set_name, only: [:show, :edit, :update, :destroy]
  before_action :set_all_names

  # GET /names
  # GET /names.json
  def index
    @names = Name.all
  end

  # GET /names/1
  # GET /names/1.json
  def show
  end

  # GET /names/new
  def new
    @name = Name.new
  end

  # GET /names/1/edit
  def edit
  end

  # POST /names
  # POST /names.json
  def create
    @name = Name.new(name_params)
    if @name.save
      flash[:notice] = "Saved successfully."
    else
      flash[:error] = "Not saved."
      redirect_to :back
    end
  end

  # PATCH/PUT /names/1
  # PATCH/PUT /names/1.json
  def update
    if @name.update(name_params)
      flash[:notice] = "Name was updated."
    else
      flash[:error] = "Something went wrong."
    end
  end

  # DELETE /names/1
  # DELETE /names/1.json
  def destroy
    @name.destroy
    flash[:notice] = "Name was successfully destroyed."
  end

  private

    def set_all_names
      @names = Name.all
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_name
      @name = Name.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def name_params
      params.require(:name).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ajaxify</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/names/_form.html.erb
<%= form_for(@name, remote: true) do |f| %>
  <% if @name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@name.errors.count, "error") %> prohibited this name from being saved:</h2>

      <ul>
      <% @name.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/names/_name.html.erb
<tr id="<%= dom_id(name) %>">
  <td><%= name.name %></td>
  <td><%= link_to 'Edit', edit_name_path(name), remote: true, name: name %></td>
  <td><%= link_to 'Destroy', name, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
</tr>

app/views/names/create.js.erb
$(".names-list").html('<%= j (render @names) %>');
$("#form").html("");

app/views/names/destroy.js.erb
$(".names-list").html('<%= j (render @names) %>');

app/views/names/edit.js.erb
$("#<%= dom_id(@name) %>").append('<td><%= j render("form") %></td>');

app/views/names/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Names</h1>

<%= link_to 'New Name', new_name_path, remote: true %>

<div id="form">
</div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="names-list">
    <%= render @names %>
  </tbody>
</table>

app/views/names/new.js.erb
$("#form").html('<%= j render("form") %>');

app/views/names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @name.name %>
</p>

<%= link_to 'Edit', edit_name_path(@name) %> |
<%= link_to 'Back', names_path %>

app/views/names/update.js.erb
$(".names-list").html('<%= j (render @names) %>');